services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - .postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classroom-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_DB}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network

  # redis:
  #     container_name: redis-fak
  #     image: redis
  #     restart: unless-stopped
  #     ports:
  #       - 6379:6379
  #     networks:
  #       - app-network

networks:
  app-network:
    driver: bridge
